name: trading_journal
description: "Log trades, strategies, and outcomes. Analyze performance over time."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+4

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.4.1
  sembast_web: ^2.4.1
  path: ^1.9.0
  fl_chart: ^0.70.2
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.0+3
  pie_chart: ^5.4.0
  pdf: ^3.11.2
  path_provider: ^2.1.5
  csv: ^6.0.0
  open_file: ^3.5.10
  url_launcher: ^6.3.1
  in_app_review: ^2.0.10
  share_plus: ^10.1.4
  google_mobile_ads: ^5.3.1
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.5.2
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"  # Add this
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Bold.ttf
         - asset: assets/fonts/Poppins-Medium.ttf
         - asset: assets/fonts/Poppins-Regular.ttf
         - asset: assets/fonts/Poppins-Thin.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
